services:
  # demo-db:
  #   container_name: demo-db
  #   image: postgres:17.2
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 00000000-0000-0000-0000-919333ac7aaf
  #     POSTGRES_DB: demo_db
  #   ports:
  #     - 5432:5432

  demo-db-mssql:
    container_name: demo-db-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 00000000-0000-0000-0000-919333ac7aaf # you can use then use this with SA user
    ports:
      - 1433:1433
