name: Deploy IAC on Azure
run-name: CI/CD ${{ github.event_name }} by @${{ github.actor }}

# Controls when the action will run
on:
  push:
    paths:
      - 'iac/**'
    branches:
      - main

# Workflows of the pipeline
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        TF_VERSION: 1.9.8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDENTIALS }}

      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform initialization
        run: terraform init
        working-directory: ./iac/

      - name: Terraform validate
        run: terraform validate
        working-directory: ./iac/

      - name: Terraform plan
        run: terraform plan -var="sql_pass=${{ secrets.TF_VAR_DB_PASSWORD }}" -out=tfplan
        working-directory: ./iac/

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./iac/

      - name: Notify failure
        if: failure()
        run: echo "Terraform apply failed for ${{ github.ref_name }}"