name: Build and Deploy API on Azure
run-name: CI/CD ${{ github.event_name }} by @${{ github.actor }}

# Controls when the action will run
on:
  workflow_dispatch:
  push:
    branches:
      - main

# Workflows of the pipeline
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      id: github
      uses: actions/Checkout@v3

    - name: Setup WebApi .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Configure Azure Container Registry (ACR)
      uses: azure/docker-login@v2
      with:
        login-server: ${{ vars.ACR_SERVER }}
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Get commit SHA
      id: vars
      run: |
        getSha=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$getSha"

    - name: Build and push image to Azure Container Registry (ACR)
      env:
        ACR_REGISTRY: ${{ vars.ACR_SERVER }}
        IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
      run: |
        docker build -f Dockerfile -t $ARC_REGISTRY/demoacrdev:IMAGE_TAG -t $ARC_REGISTRY/demoacrdev:latest .
        docker push $ACR_REGISTRY/demoacrdev --all-tags